name: wehealth
description: A new Flutter project.
#
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 50.7.3+101

environment:
  sdk: ">=3.0.5 <4.0.0"

# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.13
  dio: ^4.0.6
  flutter_screenutil: ^5.8.1
  fluttertoast: ^8.2.2
  get: ^4.6.5
  get_it: ^7.2.0
  pin_code_fields: ^7.4.0
  google_sign_in: ^5.4.1
  http: ^0.13.5
  # flutter_facebook_auth: ^5.0.1
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.1
  syncfusion_flutter_gauges: ^20.2.46
  firebase_messaging: ^14.6.1
  flutter_local_notifications: ^12.0.3
  intl: ^0.18.0
  flutter_material_color_picker: ^1.1.0+2
  webview_flutter: ^3.0.4
  syncfusion_flutter_charts: ^20.3.52
  flutter_speed_dial: ^6.2.0
  image_picker: ^0.8.6
  path_provider: ^2.0.13
  twilio_programmable_video: ^1.1.1
  social_share: ^2.3.1
  health: ^4.4.0
  device_info_plus: ^8.1.0

  url_launcher: ^6.1.7
  youtube_player_iframe: ^3.1.0
  flutter_pdfview: ^1.2.5
  dots_indicator: ^2.1.0
  # pdfx: ^2.3.0
  flutter_native_splash: ^2.2.17
  permission_handler: ^10.2.0
  flutter_blue_plus: ^1.30.3
  scroll_date_picker: ^3.6.1
  collection: ^1.17.0
  wakelock: ^0.6.2
  path: ^1.8.2
  file_picker: ^5.2.6
  provider: ^6.1.1
  # pdf: ^3.9.0
  # flutter_blue_plus: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # rules and activating additional ones.
  flutter_lints: ^2.0.1

# The following section is specific to Flutter.
flutter:
  # the material Icons class.
  uses-material-design: true

  #
  assets:
    - assets/pdfs/
    - assets/languages/
    - assets/flags/
    - assets/icons/
    - assets/images/
    - assets/icons/login/
    # - assets/icons/medicine_shape/
    - assets/icons/shape/
    - assets/icons/home/
    - assets/icons/social/
    - assets/icons/devices/
    - assets/icons/devices/new_device/
    - assets/splashscreen/

  # example:
  fonts:
    - family: montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular-400.ttf
    - family: roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
