class CustomStrings {
  static const String aboutUs =
      '''UMCH Technology Sdn. Bhd. formerly known as UMMH Medical Home Sdn. Bhd., an incubator company specializing in connected fitness, wellness and healthcare technology solutions, nurtured by the University of Malaya, under the leadership of Professor Dr. Loo Chu Kiong, an academic professor in the Department of Artificial Intelligence, Faculty of Computer Science And Information Technology of University Malaya and Teoh Seng Jing who is a serial entrepreneur. The Company aspires to become the regional leader in providing 
    highly relevant and effective fitness, wellness and healthy living solutions. We “re-engineer” disrupt” existing models the healthcare delivery system by empowering the individual to take charge of their own health at home and link them up with preventive healthcare strategies from our panel of fitness and health professionals at an affordable cost. 
    We are working on several innovative and pioneering solutions that integrate hardware, firmware, domain intelligence, big data management and healthy living needs into easily assessable, highly mobile and well integrated products. Our Multi-Awards winning solution, Connected Healthcare Integrated Fitness CHIEF is a mobile solution for managing a healthy lifestyle through systematic tracking of user’s activities. We innovated CHIEF based on the concept to create a need and motivation for users to continuously engage in long term behavioural change. 
    CHIEF implements a “supportive accountability framework”, allowing fitness trainers to view the user's daily logs and offer feedback. The app tracks a number of metrics such as Physical Activity, Diet, Body And Mental Activity, providing a more accurate and comprehensive view for health professionals. Users would be motivated to stay healthy through consistent feedback from a network of health professionals. CHIEF innovative solutions are supported by strong Intellectual Property Rights. The team comprises of highly skilled IT workers with more 
    than 20 years of experience in Healthcare IT, working together with a team of researchers from acclaimed university in Malaysia, University of Malaya. The solution has been implemented and commercialized, successful results from Corporate Fitness Program whereby participants have shown remarkable weight loss of up to 20kg in 4 months. The ease of application and having a mobile buddy that tracks and motivates you towards positive behavioral changes has increased the demand for our app. UMCH Technology is a recipient of Cradle Fund Sdn Bhd'sCoach 
    and Grow Programme in year 2015. UMCH Technology is also a recipient of the High Impact Programme 2 which is managed by PlaTCOM Ventures Sdn Bhd, a wholly owned subsidiary of Agensi Inovasi Malaysia formed in collaboration with SME Corp. Malaysia. UMCH Technology will receive an end-to-end facilitation which includes product development, productisation, 
    licensing support, regulatory certification, technical and financial assistance under the High Impact Programme 2, a national initiative under the SME Masterplan 2012-2020''';

  static const String contactUs =
      '''You can track your activity, weight, food intake, blood pressure, blood glucose, heart rate, oxygen concentration, sleep and mind's progress to help you stay on the path of fitness''';
}
